language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
script: nosetests -v
sudo: false
notifications:
  recipients:
    - isn@extrn.org
  email:
    on_success: change
    on_failure: always
